import AdminNav from "@/components/AdminNav";
import { Inter } from "next/font/google";
import Script from 'next/script'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Admin Page",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AdminNav />
                {children}
                {/* Use next/script with a non-blocking strategy instead of synchronous <script> tags */}
                <Script src="https://cdn.lordicon.com/lordicon.js" strategy="afterInteractive" />
                <Script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module" strategy="afterInteractive" />
            </body>
        </html>
    );
}
