import AdminNav from "@/components/AdminNav";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Admin Page",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AdminNav />
                {children}
                <script src="https://cdn.lordicon.com/lordicon.js"></script>
                <script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module"></script>
            </body>
        </html>
    );
}
